swagger: "2.0"
info:
  version: 1.0.0
  title: Factura Tracker API
  description: Seguimiento de deudas de facturas
basePath: /api/v1
tags:
  - name: Specification
    description: The swagger API specification
  - name: Oficinas
    descripcion: Endpoints para la gestión de oficinas
  - name: Usuarios
    descripcion: Endpoints para la gestión de usuarios
  - name: Reglas
    descripcion: Endpoints para la gestión de reglas
  - name: Deudas
    descripcion: Endpoints para la gestión de deudas

consumes:
  - application/json
produces:
  - application/json

# TODO: Separar definiciones para create y para update
definitions:
  UsuarioBody:
    type: object
    title: usuario
    properties:
      nombre:
        type: string
        example: Esteban
      apellido:
        type: string
        example: Massuh
      email:
        type: string
        example: massuhe@gmail.com
      oficina:
        type: string
  OficinaBody:
    type: object
    title: oficina
    properties:
      nombre:
        type: string
        example: 5-1
  ReglaBody:
    type: object
    title: regla
    properties:
      descripcion:
        type: string
        example: Llegar tarde
      prenda:
        type: string
        example: Pagar facturas
  DeudaBody:
    type: object
    title: deuda
    properties:
      deudor:
        type: string
        example: Id del usuario deudor
      reglaInflingida:
        type: string
        exmaple: Id de la regla inflingida
      fiscal:
        type: string
        example: Id del usuario fiscal
      fechaPago:
        type: date

paths:
  # --------- USUARIOS --------- #
  /usuarios:
    get:
      tags:
        - Usuarios
      descripcion: Devuelve todos los usuarios
    post:
      tags:
        - Usuarios
      description: Crea un nuevo usuario
      parameters:
        - name: usuario
          in: body
          descripcion: Datos del nuevo usuario
          required: true
          schema:
            $ref: "#/definitions/UsuarioBody"

  /usuarios/{id}:
    get:
      tags:
        - Usuarios
      parameters:
        - name: id
          in: path
          required: true
          description: El id del usuario a recuperar
          type: string
    patch:
      tags:
        - Usuarios
      parameters:
        - name: id
          in: path
          required: true
          description: El id del usuario a actualizar
          type: string
        - name: usuario
          in: body
          description: Datos del usuario a actualizar
          required: true
          schema:
            $ref: "#/definitions/UsuarioBody"
    delete:
      tags:
        - Usuarios
      parameters:
        - name: id
          in: path
          required: true
          description: El id del usuario a eliminar
          type: string
  # --------- OFICINAS --------- #
  /oficinas:
    get:
      tags:
        - Oficinas
      description: Devuelve todas las oficinas
    post:
      tags:
        - Oficinas
      description: Crea una nueva oficina
      parameters:
        - name: oficina
          in: body
          description: Datos de la nueva oficina
          required: true
          schema:
            $ref: "#/definitions/OficinaBody"
  
  /oficinas/{id}:
    get:
      tags:
        - Oficinas
      parameters:
        - name: id
          in: path
          required: true
          description: Id de la oficina a recuperar
          type: string
    patch:
      tags:
        - Oficinas
      parameters:
        - name: id
          in: path
          required: true
          description: El id del usuario a actualizar
          type: string
        - name: oficina
          in: body
          description: Datos de la oficina a actualizar
          required: true
          schema:
            $ref: "#/definitions/OficinaBody"
    delete:
      tags:
        - Oficinas
      parameters:
        - name: id
          in: path
          required: true
          description: El id de la oficina a eliminar
          type: string
  # --------- REGLAS --------- #
  /oficinas/{id}/reglas:
    get:
      tags:
        - Reglas
      parameters:
        - name: id
          in: path
          required: true
          description: Id de la oficina cuyas reglas se recuperarán
          type: string
    post:
      tags:
        - Reglas
      parameters:
        - name: id
          in: path
          required: true
          description: El id de de la oficina a la que se le agregará la regla
          type: string
        - name: regla
          in: body
          description: Datos de la regla a agregar
          required: true
          schema:
            $ref: "#/definitions/ReglaBody"
  /oficinas/{oficina}/reglas/{id}:
    patch:
      tags:
        - Reglas
      parameters:
        - name: id
          in: path
          required: true
          description: Id de la regla a actualizar
          type: string
        - name: oficina
          in: path
          required: true
          description: Id de la oficina que contiene la regla a actualizar
          type: string
        - name: regla
          in: body
          required: true
          description: Datos de la regla a actualizar
          type: object
          schema:
            $ref: "#/definitions/ReglaBody"
    delete:
      tags:
        - Reglas
      parameters:
        - name: id
          in: path
          required: true
          description: Id de la regla a eliminar
          type: string
        - name: oficina
          in: path
          required: true
          description: Id de la oficina que contiene la regla a eliminar
          type: string
  # --------- DEUDAS --------- #
  /oficinas/{id}/deudas:
    get:
      tags:
        - Deudas
      parameters:
        - name: id
          in: path
          required: true
          description: Id de la oficina cuyas deudas se recuperarán
          type: string
    post:
      tags:
        - Deudas
      parameters:
        - name: id
          in: path
          required: true
          description: El id de de la oficina a la que se le agregará la deuda
          type: string
        - name: deuda
          in: body
          description: Datos de la deuda a agregar
          required: true
          schema:
            $ref: "#/definitions/DeudaBody"
  /oficinas/{oficina}/deudas/{id}:
    patch:
      tags:
        - Deudas
      parameters:
        - name: id
          in: path
          required: true
          description: Id de la deuda a actualizar
          type: string
        - name: oficina
          in: path
          required: true
          description: Id de la oficina que contiene la deuda a actualizar
          type: string
        - name: deuda
          in: body
          required: true
          description: Datos de la deuda a actualizar
          type: object
          schema:
            $ref: "#/definitions/DeudaBody"
    delete:
      tags:
        - Deuda
      parameters:
        - name: id
          in: path
          required: true
          description: Id de la deuda a eliminar
          type: string
        - name: oficina
          in: path
          required: true
          description: Id de la oficina que contiene la deuda a eliminar
          type: string
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

  # /examples:
  #   get:
  #     tags:
  #       - Examples
  #     description: Fetch all examples
  #     responses:
  #       200:
  #         description: Returns all examples
  #   post:
  #     tags:
  #       - Examples
  #     description: Create a new example
  #     parameters:
  #       - name: example
  #         in: body
  #         description: an example
  #         required: true
  #         schema: 
  #           $ref: "#/definitions/ExampleBody"
  #     responses:
  #       200:
  #         description: Returns all examples

  # /examples/{id}:
  #   get:
  #     tags:
  #       - Examples
  #     parameters:
  #       - name: id
  #         in: path
  #         required: true
  #         description: The id of the example to retrieve
  #         type: integer
  #     responses:
  #       200:
  #         description: Return the example with the specified id
  #       404:
  #         description: Example not found